### PR TITLE
Change some styles on list-item element

### PR DESCRIPTION
**Pull request by gponsu**

### CODE REVIEW

**Comment by scruti** [comment]
:+1:

**Comment by d2bit** [comment]
:+1:

**Comment by Fernan2** [comment]
As Xavi Gost says, "refactor means changing the code without modifying the observable behavior", so the PR title is wrong; all else is fine for me

**Comment by gponsu** [comment]
External behavior that I've changed?

**Comment by Fernan2** [comment]
Changing margins or fonts is changing the external behavior by definition, just paste screenshots of old vs new and the changes are apparent at a glance..

**Pull request merged**
