### PR TITLE
Add changes to style user edit page.

### PR DESCRIPTION
**Pull request by gponsu**

### CODE REVIEW

**Comment by scruti** [comment]
:+1:  :see_no_evil:

**Comment by d2bit** [comment]
:+1: but a screenshot should be great!

**Comment by gponsu** [comment]
screencapture-localhost-3001-usuarios-editar-fernan2

**Comment by Fernan2** [comment]
Late +1 for the styles... not for the screenshot, as those aren't the fields that our users have. Don't rely blindly on the designs, nor on any muggle's request, they always lie

**Pull request merged**
