### PR TITLE
Allow navigation element to set item icons

### PR DESCRIPTION
**Pull request by d2bit**
```ruby
{
  name: 'Inicio',
 url: main_app.home_path,
 icon: 'home',
 title: ESTA_WEB
},
{
  name: 'Foros',
  url: main_app.portada_foros_path,
  active: active_foros?,
  submenu: mobile_menu_foros,
  title: "Tu foro en los foros de #{ ESTA_WEB }"
}
```
captura de pantalla de 2015-05-20 18 48 58

### CODE REVIEW

**Comment by Fernan2** [comment]
+1

**Comment by gponsu** [comment]
:+1

**Comment by scruti** [comment]
:+1:

**Comment by maxvlc** [comment]
:+1:

**Pull request merged**
