### PR TITLE
Merged design elements into one unique haml

### PR DESCRIPTION
**Pull request by Dygerydoo**
Setting up guide navigation to properly render sections

### CODE REVIEW

**Comment by Fernan2** [comment]
screenshot, please... :pray:

**Comment by Dygerydoo** [comment]
@Fernan2 Is the same, but merged into a unique haml, anything has changed ;)

styleguide

The color cards are not the same because no I have a problem with the name of their classes but the styles are the same.

**Comment by Fernan2** [comment]
If you're joining 3 blocks in a single view, maybe it could be a good idea to keep the old structure with 3 separate files, but converting them to partials (just start the name with `_`), and let the main view to render them.. all in a big file makes it a bit too big.

**Comment by d2bit** [comment]
:+1: maybe it can be extracted to partials for sections as @Fernan2 said.

**Comment by Dygerydoo** [comment]
@Fernan2 and @d2bit it's done! Merge??

**Comment by Fernan2** [comment]
+1

**Comment by maxvlc** [comment]
:+1:

**Pull request merged**
